activemq:
  image: kareemsait/activemq-metrics
  pullPolicy: IfNotPresent

namespace: default

serviceType: NodePort

replicas: 1

metrics:
  enabled: false
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
