apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-ui
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8161
      targetPort: 8161
  selector:
    app: {{ template "fullname" . }}
  type: NodePort
