apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      serviceAccountName: {{ template "fullname" . }}
      containers:
      - name: {{ template "fullname" . }}
        image: {{ .Values.activemq.image }}
        imagePullPolicy: {{ .Values.activemq.pullPolicy }}
        ports:
        - containerPort: 8161
        - containerPort: 61616
        - containerPort: 5672
        - containerPort: 61613
        - containerPort: 1883
        - containerPort: 61614
        {{- if .Values.metrics.enabled }}
        - containerPort: 9000
        {{- end }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PODLABELKEY
          value: 'app'
        - name: PODLABELVALUE
          value: '{{ template "fullname" . }}'